### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by KidkArolis** [tildeio/rsvp.js#104]
I used to install rsvp.js with bower, but I can't anymore since "dist" has been removed from the repo. Any plans to add that back in?

**Comment by jordanthornquest** [comment]
Having this same issue with `3.0.17`. For someone like me using `grunt-wiredep`, RSVP doesn't show up as it should because there's no `dist/rsvp.js` to be found :)

**Comment by mikepmunroe** [comment]
@delta98 @jordanthornquest, can you confirm if this is a still a problem for you? 

I just tried and could not repo, but I suspect you have a more specific case that fails. 

```
bower install rsvp
bower rsvp#*                not-cached git://github.com/components/rsvp.js.git#*
bower rsvp#*                   resolve git://github.com/components/rsvp.js.git#*
bower rsvp#*                  download https://github.com/components/rsvp.js/archive/3.0.17.tar.gz
bower rsvp#*                   extract archive.tar.gz
bower rsvp#*                  resolved git://github.com/components/rsvp.js.git#3.0.17
bower rsvp#~3.0.17             install rsvp#3.0.17
```

Any more info you could provide on a more specific repo case might help.

**Comment by StoatPower** [comment]
Bower installation is still failing. Manually changing the "main": "dist/rsvp.js" in bower.json to "main": "rsvp.js" of the rsvp.js bower_component resolves the issue, so I'm assuming just making that change here in the repo is all that needs to happen?

**Comment by jordanthornquest** [comment]
It doesn't seem to be anything special on my end. Doing what @StoatPower suggests fixes my problem, and the `bower.json` [here](https://github.com/tildeio/rsvp.js/blob/master/bower.json) on the repo seems to be looking for a `dist/rsvp.js`, which doesn't exist on the `bower install`ed version of **rsvp.js**.
