### ISSUE TITLE
long stack traces

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/rsvp.js#135]

**Comment by Taytay** [comment]
We love RSVP, but I'm in the midst of debugging some pretty hairy promises code, and boy, would long stack traces make my life easier. :) Is progress stalled on that Chromium issues?

**Comment by stefanpenner** [comment]
the chromium issue would make us not have to implement it at all, in-addition when using the chrome dev-tools the stack-explorer would work during debugging. Which would be lovely.

**Comment by bnolan** [comment]
Hey, I would love this. I cannot see what line of systemjs-builder has called an invalid command, because there are no stack traces, just the error message. It's a very terrible debugging experience.

**Comment by bnolan** [comment]
None of these calls show anything useful about the error, am I doing something wrong?

===
var util = require('gulp-util');
var jspm = require('jspm');
var path = require('path');

function bundle () {
    var builder = new jspm.Builder(path.join(__dirname, 'src'));

    return builder.loadConfig('./src/config.js')
        .then(function () {
            return builder.bundle('app/index').catch(function (error) {
                console.error(error.stack);
                console.log(JSON.stringify(error));
                console.log(JSON.stringify(arguments));
                console.log(JSON.stringify(Object.keys(error)));
                console.error(error);
            });
        })
===

**Comment by stefanpenner** [comment]
looks like console.tagStack may merge with the zones.js proposal.

**Comment by stefanpenner** [comment]
After further thought (and experimentation) addressing long-stacks here still leaves one craving more. For example, stitching across others forms of async unrelated to this library.

Now, I believe this still may eventually be added here. But I do not believe it urgent, nor a bug that we do not yet implement this.
 
For my own personal debugging, https://github.com/mattinsler/longjohn has been fantastic, as not only does it stitch RSVP promises stacks back together, but it stitches all async gaps together.

The downside is the stacks end up more verbose, the upside we get all the information.

Again, I may revisit this in RSVP in the future. But having a whole system solution without any gaps ala longjohn seems like a good approach.
