### ISSUE TITLE
Error on "missing" module: vertx

### ISSUE THREAD

**Issue by joshlasdin** [tildeio/rsvp.js#352]
When including RSVP in my browserify bundle, I get the following error:

```
Error: Cannot find module 'vertx' from '/Volumes/Server/pldgit-app/node_modules/rsvp/dist'
```

There is no such issue in v `3.0.14`. Looking in the npm distributed source (`node_modules/rsvp/dist/rsvp.js`), looks like it does `require('vertx')`, but no such file or sub-module exists, however there is a file in the root called vertx.js. Changing this line to `require('../vertx') fixes the issue.

**Comment by BenjaminPrice** [comment]
Any update on when this fix may be released?
