### ISSUE TITLE
rsvp.js.map is throwing a 404

### ISSUE THREAD

**Issue by ziaukhan** [tildeio/rsvp.js#357]
Playing around with the newest rsvp.js today, I'm noticing that rsvp.js.map is showing up as a 404 when putting the rsvp.js (3.0.16) script into a site that I'm working on.

I don't see a source map file in the bower distribution.

Ideas as to solving? I am using RSVP with geoFire, angularGeoFire, etc.

Thanks

**Comment by ShahzadSoomro** [comment]
+1

**Comment by Maluen** [comment]
Same here

**Comment by stefanpenner** [comment]
did you include the provided map file?

**Comment by teddyzeenny** [comment]
I don't think there's a map file.
