### ISSUE TITLE
Fails with browserify

### ISSUE THREAD

**Issue by AgentME** [tildeio/rsvp.js#358]
If I try to use RSVP 3.0.16 with Browserify, I get an error. 3.0.14 worked.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'vertx' from '[...]/node_modules/rsvp/dist'
```

**Comment by stefanpenner** [comment]
duplicate: https://github.com/tildeio/rsvp.js/search?q=browserify&type=Issues&utf8=%E2%9C%93 please  search before you open an issue.

resolution:

* browserify -x vertx
* its fixed on master, pending release (Cc @fivetanley  got time?)

**Comment by AgentME** [comment]
Sorry, I only scrolled through the open issues.
