### ISSUE TITLE
Add "auto" function.

### ISSUE THREAD

**Issue by flyswatter** [tildeio/rsvp.js#359]
The coolest feature that [async](https://www.npmjs.com/package/async) has that `RSVP` (or any promise library I know of) lacks is the [auto](https://www.npmjs.com/package/async#auto) function.

It would work like `RSVP.hash` except the value for each key could optionally be an array where the last argument is a promise returning function, and the previous arguments are the names of keys of other promises in the hash whose values should resolve before that promise-returning function is called.

Naturally, the promise-returning function receives the latest results hash as its only argument.

Sample usage, where to create a new post, a user must be authenticated, but also to
```javascript
var self = this

Em.RSVP.auto({
  parentTopic: this.get('post.parentTopic'),
  authenticate: this.authenticateUser({id: id}),
  submitPost: ['parentTopic', 'authenticate', function (results) {
    var authenticatedUser = results.authenticate
    var parentTopic = results.parentTopic
    var newPost = self.store.createRecord( 'post', {
      topic: parentTopic,
      author: authenticatedUser
    })
    return newPost.save()
  }]
}).then(function(results){
  var newPost = results.newPost
})
```

**Comment by stefanpenner** [comment]
isn't this just: ?

```js
Em.RSVP.hash({
  parentTopic: this.get('post.parentTopic'),
  authenticate: this.authenticateUser({id: id}),
}).then(function(results){ 
    var authenticatedUser = results.authenticate
    var parentTopic = results.parentTopic
    var newPost = self.store.createRecord( 'post', {
      topic: parentTopic,
      author: authenticatedUser
    })
    return newPost.save()
  }]
});
```

**Comment by flyswatter** [comment]
Yeah, your way achieves the same goal as my example, and demonstrates how simple my example was.

The `auto` function is most useful when is a large series of dependent async functions, each with different async dependencies.  With a more complex graph, the benefits become more and more clear.

It might just be the case that client-side async functions tend to be simpler, and so the needs aren't as obvious, but as a primarly node-based developer, `async.auto` has become my best friend.  It's a series, it's parallel, it's all the methods you could need from an async library in a single method.

**Comment by stefanpenner** [comment]
@flyswatter ah, I see. Mind providing a-few more examples? It is highly unlikely, that this will be added to  rsvp, but i am in the process of reviving rsvp-party, which aims to be a kitchen-sink of helpers and useful functions.  https://github.com/stefanpenner/rsvp-party/pull/9

**Comment by flyswatter** [comment]
Sure, I'll open an rfc there at some point.  First, another couple examples here:

Say you had a few tasks you liked to perform in a row.  It works a lot like `RSVP.hash`:

```javascript
RSVP.auto({
  first: first(),
  second: second(),
  third: third(),
});
```
But what if you suddenly realized your third step needed to wait on your second step?  You could make this simple change:
```javascript
RSVP.auto({
  first: first(),
  second: second(),
  third: ['second', third()],
});
```
Now the `first` and `second` promises resolve simultaneously, and the `third` waits for the `second` to resolve.  If the first takes a long time, it's possible for the `third` to resolve before the `first`!

Now, you might say hey, this is very similar to just saying:
RSVP.hash({
  first: first(),
  third: second().then(third),
});
```
And it is, so here's a more complicated example:
```javascript
RSVP.auto({
  userAccount: getAccount(),
  userPermissions: ['userAccount', getPermissions()],
  posts: ['userAccount', getPosts()],
  replies: ['posts', getReplies()],
  ownReplies: ['userAccount', 'replies', getOwnReplies()]
});
```
Here we have a semi-realistic scenario, where we're loading the initial state for an application.

The app loads the user account first, and once the user account is loaded, posts and permissions are loaded.  Once posts are loaded, replies are loaded, and getting a person's own replies requires both that user's account *and* the list of replies, so it will tend to fire last.

This isn't too complex, and would be writable in normal promise ways, it would just be a little tricky.

Where the `auto` function really shines is when you have to modify complicated async flows.  Say for example, I suddenly realized I need to get author avatars after loading posts.  I can just write that function, and add:
```javascript
RSVP.auto({
  userAccount: getAccount(),
  userPermissions: ['userAccount', getPermissions()],
  posts: ['userAccount', getPosts()],
  avatars: ['posts', getAvatars()],  // One line to insert an async method into a web of other functions.
  replies: ['posts', getReplies()],
  ownReplies: ['userAccount', 'replies', getOwnReplies()]
});
```
I think this is a pretty good example of how `auto` can shine.  Anyways, I'll try writing an RPC at some point on your party page, just getting some examples out there now.

**Comment by stefanpenner** [comment]
I suspect each of your `getFoo()` should be `getFoo` so the tool can invoke based on the appropriate order?

Do you also expect recursive resolution?

**Comment by flyswatter** [comment]
Yeah, my mistake, those shouldn't be called in the array.

I'm not sure how recursive resolution would work here.  Since each thing either has zero or more dependencies, and wait for all of their dependencies to complete before firing, if two things list each other as dependencies, neither will ever fire.

**Comment by stefanpenner** [comment]
@flyswatter a dag can be created to resort most issues. :P

**Comment by flyswatter** [comment]
What's a dag?

**Comment by mixonic** [comment]
@flyswatter directed acyclic graph -> http://en.wikipedia.org/wiki/Directed_acyclic_graph
