### ISSUE TITLE
Chained promise aggregators

### ISSUE THREAD

**Issue by deepan83** [tildeio/rsvp.js#360]
Are there any plans to support a chained promise aggregator(either through an array or a object hash) that resolves promises in the order they have been setup? The current all and hash methods are promise aggregators that resolve when all promises in them are resolved but not necessarily in any particular order.Can be achieved by "thenning" but would be great if there was a built in method that did it under the hood.

**Comment by stefanpenner** [comment]
a promise is the resulting value, once you have a promise it is basically to "late" to re-order. You likely want some `task` system layered on top.

The simplest would be something like https://github.com/joliss/promise-map-series

Please let me know if i mis-understood you

**Comment by deepan83** [comment]
Yeah thats the kind of task system I meant (apologises for the unclear original description)
Are there any plans to support an iterator of that sort in RSVP?

**Comment by stefanpenner** [comment]
We will soon support es2015 iterables.

**Comment by teddyzeenny** [comment]
There's a good chance I misunderstood, but you can order tasks using reduce:

```javascript
// Untested code
let registration = students.reduce((promise, student) => {
  return promise.finally(() => student.register());
}, Promise.resolve());
```
