### ISSUE TITLE
Feature request: shortcut to create prefulfilled and prerejected promises

### ISSUE THREAD

**Issue by lolmaus** [tildeio/rsvp.js#363]
I've discovered that `.then( function() {}, function() {} )` returns a positively resolved promise even if the initial promise was rejected, while `.then( function() {} )` would return a rejected promise. This is counter-intuitive to me, but i guess this is how ES6 is designed, so it's useless to whine about it.

Anyway, to work this around, i have to explicitly return a rejected promise from the failure callback of `.then()`:

```js
return somePromise .then(
  function(data) {
    // Success
    return data;
  },
  function(data) {
    // Failure
    var rejectedPromise = new RSVP.Promise(
      function (resolve, reject) {
        reject(data);
      }
    );
    return rejectedPromise;
  };
);
```

This is a terrible amount of code to write. I can think of this instead:

```js
return somePromise .then(
  function(data) {
    // Success
    return data;
  },
  function(data) {
    // Failure
    return RSVP.rejectedPromise(data);
  };
);
```

**Comment by stefanpenner** [comment]
reduced your above example:

```js
return somePromise.then(function(data) {
  return data;
}, function(reason) {
  throw reason;
});
```

Additionally, the following short-hands exist.

```js
var fulfilled = RSVP.Promise.resolve(data);
var rejected = RSVP.Promise.reject(reason);
```

**Comment by lolmaus** [comment]
> `throw reason;`

Oh, i didn't know that promises catch all errors thrown from inside `then` callbacks. I thought they would leak. Learning every day! :D


> Additionally, the following short-hands exist.

Thank you, @stefanpenner! This is exactly what i wanted.

My teammate @gleb-osokin told me that those exist already, but we failed to find them mentioned in RSVP readme. Why are they not mentioned?

**Comment by domenic** [comment]
Just as a reminder, `doX().then(function () { }, doY)` is the asynchronous equivalent of `try { doX() } catch (e) { doY(e); }` so if `doY` is an empty function then the error will be swallowed whereas if `doY` is a function that re-throws the exception then the error will be propagated. Hope this helps your conceptual model.

**Comment by stefanpenner** [comment]
> My teammate @gleb-osokin told me that those exist already, but we failed to find them mentioned in RSVP readme. Why are they not mentioned?

They should likely be added to the README, so that future travelers to the promised land will catch them. 

We should really get an RSVP site up, which can contain its own docs. But for reference they do exist as part of ember http://emberjs.com/api/classes/RSVP.html

**Comment by lolmaus** [comment]
@domenic, @stefanpenner, you guys rock!

**Comment by stefanpenner** [comment]
@domenic thanks.

from a past talk I gave:

![screen shot 2015-02-06 at 10 10 31 am](https://cloud.githubusercontent.com/assets/1377/6081550/6b599178-ade8-11e4-93f0-fbc6e4bfcefd.png)

link to the deck: http://static.iamstef.net/promise.pdf

**Comment by stefanpenner** [comment]
for the most part though, i strongly recommend people use the following form:

```js
promise.then(function(value) {

}).catch(function(reason) {

});
```

as it is mostly what people actually what to use.
