### ISSUE TITLE
possible divergence from ES6 spec?

### ISSUE THREAD

**Issue by getify** [tildeio/rsvp.js#365]
Trying this with native ES6 browser implementation of `Promise`:

```js
var p1 = Promise.resolve(42);
var p2 = p1.then();

p1 === p2;    // false
```

That's I believe because of [ES6: 25.4.5.3.5](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise.prototype.then) which seems to always vend a new promise instance from a `then(..)` call, even if there's no arguments passed to it.

However, trying that with *rsvp* seems to produce `true`. [Promises/A+ note 3.3](https://promisesaplus.com/#point-71) says:

> Implementations may allow promise2 === promise1

And from [promise.js, line 387](https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp/promise.js#L387), it appears this lib is taking that option.

I'm not sure that's wise though, since it follows the loophole provided by A+ but appears to diverge from the stricter ES6 spec. At least as far as people look to this library as a standard ES6 polyfill, I think they'd expect it to follow the ES6 spec if there's any case (like it seems with this one) where there could be divergence from the A+ spec.

Apologies if I've analyzed this wrong, was just a quick rough pass based on a tweet I received. Just something to consider/look into.

**Comment by calvinmetcalf** [comment]
May be am issue to file on the a plus spec

**Comment by stefanpenner** [comment]
> Apologies if I've analyzed this wrong, was just a quick rough pass based on a tweet I received. Just something to consider/look into.

You have analyzed this correctly.

Some context: After @calvinmetcalf submitted this short-cut I had a chat with @domenic, we both agreed it was obviously a violation but were curious as to how it played out in the wild. So as an experiment we pulled it in. So far no obvious issues have arisen, other then an obvious strict adherence violation.

**Comment by stefanpenner** [comment]
> May be am issue to file on the a plus spec

Ya, I suspect the a/+ spec should become a proper subset of ES2015

**Comment by getify** [comment]
@stefanpenner Thanks for the info.

Some other context: [a tweet I sent](https://twitter.com/getify/status/563983918819311616) out last nite:

> #protip want to fork a promise into another one of the same state (for observation)? call `then()` with no params:
> 
> var newpr = oldpr.then();

@calvinmetcalf pointed out that this would not necessarily be true of promise/a+ libs, though we've clarified it would be true of native promises. So that's at least one context for a benefit.

**Comment by stefanpenner** [comment]
The optimization is a nice little trick for some scenarios. I can be convinced that it should be removed.

**Comment by getify** [comment]
I would be curious what use case there is for it?

```js
p1 === p1.then()
```

In any case where you already have `p1`, why do you want to call an identity function on it to get it right back? That extra function call seems wasteful perf-wise. What am I missing?

**Comment by calvinmetcalf** [comment]
The then doesn't have to be empty if it only has a success handler and it's
already rejected or vis versa

**Comment by getify** [comment]
To clarify, are you saying these two snippets would have **exactly** the same behavior (in terms of number of promises created explicitly or implicitly, sequencing on the Job queue, etc):

```js
var p = Promise.resolve(42);

p
.then(function(){ console.log("a"); })
.then(function(){ console.log("b"); });
```

```js
var p = Promise.resolve(42);

p.then(function(){ console.log("a"); })
p.then(function(){ console.log("b"); });
```

**Comment by stefanpenner** [comment]
it is not-uncommon to re-visit the same chains repeatedly (imagine navigating a website, were data becomes cached). Promises make a great DSL that works regardless of data locality, but in many cases the data is very local.

So, given the following example:

```js
something().
  .then(foo)
  .catch(handleFooFailure);
  .then(bar)
  .catch(handleBarFailure);
```

Imagine `something()` is already "local", their is no reason to re-allocate and process the 2 `catch`s as they will never be invoked, nor will they result in any side-affects.

Their is a slightly less aggressive optimizations were a more specialized follower is returned if the state is already known.

**Comment by benjamingr** [comment]
@getify `.then()` is useful if your promises have additional logic like cancellation, or progression. 

It also 'might' be useful in some cases if your initial promise was generated in an environment that allocated a big closure for the handler and now that it's done you want a clean copy containing 'just the value'.

Personally I think it's just baggage from the spec which it carries for historical reasons and should have type error'd :D

**Comment by calvinmetcalf** [comment]
@getify the optimization only hits for 

```
Promise.resolve(val).catch(fun)
Promise.reject(err).then(fun);
```

it would not make any difference for 

```
Promise.resolve(val).then(fun);
Promise.reject(err).catch(fun)
```

**Comment by mikepmunroe** [comment]
@getify @calvinmetcalf, seems like there is agreement that it is a divergence from the A+ spec, but is valid according to stricter ES6 spec. 

Should this issue be closed out or is there some scenarios that still require investigation?

**Comment by getify** [comment]
@mikepmunroe I think it's the reverse, unless I missed something... IIUC it is valid Promises/A+ but invalid ES6, at least in terms of considering RSVP as a complete spec-compliant stand-in polyfill for ES6 `Promise`.

**Comment by mikepmunroe** [comment]
@getify ah, after reading more closely, I am following. That is probably why it is still open. It's valid according to A+, but not to stricter ES6. It's possible A+ might take on the stricter ES6 rule, in this example, in the future. 

Guess it's still open to be decided by committee to fix and close this or leave it alone and close this.

**Comment by stefanpenner** [comment]
I should likely fix this. I have some cleanup planned. Just haven't had a chance to dig in yet

**Comment by stefanpenner** [comment]
Letting this stew for a year, I am still fine with this small divergence. but I understand why the spec prefers its way.
