### ISSUE TITLE
IE8 .catch() error

### ISSUE THREAD

**Issue by noel-ykt** [tildeio/rsvp.js#367]
i have this code:
```javascript
User.init()
    .catch(function () {
        ...
    }).finally(function () {
        ...
    });
```
and there is an error in the method .catch() in IE8

**Comment by stefanpenner** [comment]
`catch` and `finally` are not es3 safe. If you ship to these platforms, you must use a minifier or transpilers that re-writes them to the computed versions. Alternatively, you can also manually use the computed versions.

`eUser.init['catch']`
