### ISSUE TITLE
Using RSVP Promise as ES6 Promise polyfill

### ISSUE THREAD

**Issue by danes** [tildeio/rsvp.js#372]
Hi,

Since the RSVP promise is a superset of the ES6 spec (and the [es6-promise](https://github.com/jakearchibald/es6-promise) polyfill is basically a stripped down RSVP Promise), is it wise to use it to polyfill the global Promise object?

How would I go about using it as a polyfill?

I have a project that already includes RSVP Promises, and runs in some ES6-compliant environments, and I would like to avoid including another polyfill for native Promises.

**Comment by mixonic** [comment]
@danes the only option today is to use Ember's promise library. I want to improve this in the future, but we need to see some changes to the build pipeline first.

es6-promise should not conflict with Ember if you introduce it. You will pay the size penalty, but I don't believe there is a way around this today (short of customizing the build).

**Comment by steph643** [comment]
> Since the RSVP promise is a superset of the ES6 spec (and the es6-promise polyfill is basically a stripped down RSVP Promise), is it wise to use it to polyfill the global Promise object?
>How would I go about using it as a polyfill?

I do this ([source](https://stackoverflow.com/a/31464695/3567351)):
```javascript
window.Promise = window.Promise || Ember.RSVP.Promise
```
