### ISSUE TITLE
A release would be nice

### ISSUE THREAD

**Issue by MajorBreakfast** [tildeio/rsvp.js#374]
Since two weeks have passed since I provided [this PR](https://github.com/tildeio/rsvp.js/pull/369) a patch version bump would be nice :P

**Comment by stefanpenner** [comment]
sorry, emberconf + moving has kept me busy. Will release tonight. If i don't by tomorrow please herras me.

**Comment by MajorBreakfast** [comment]
Haha. I hope the recordings will be released soon. I'm curious :)

**Comment by stefanpenner** [comment]
@MajorBreakfast they are out!

**Comment by MajorBreakfast** [comment]
Nice. I usually rely on ember weekly for ember news and the last mail didn't include them yet. So they cannot have been out for long :P

**Comment by stefanpenner** [comment]
https://www.youtube.com/playlist?list=PLE7tQUdRKcyacwiUPs0CjPYt6tJub4xXU

i think the first ones were out march 6. Regardless I hope you enjoy.

**Comment by MajorBreakfast** [comment]
I watched your talk this morning. Was quite enjoyable :)

**Comment by stefanpenner** [comment]
sorry that it took so long

**Comment by MajorBreakfast** [comment]
Thx anyways :)
