### ISSUE TITLE
use travis's phantomjs 2

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/rsvp.js#381]
See travis-ci/travis-cookbooks@e38732d (which I see you commented on actually!?!?), and documented in http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/.

**Comment by watsonbox** [comment]
FYI this was actually [rolled back](http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/) but I guess the path change isn't doing any harm (although it's a bit misleading) until v2 is re-instated.

**Comment by stefanpenner** [comment]
Ya. Going to just leave it for now
