### ISSUE TITLE
[Question] Difference in behavior wrt Chrome native impl

### ISSUE THREAD

**Issue by vicb** [tildeio/rsvp.js#386]
consider this:

```js
      RSVP.Promise.resolve('rsvp').then(function(v) { throw v; });
      Promise.resolve('native').then(function(v) { throw v; });
```

In Chrome there would be a "Uncaught (in promise) native" exception while rsvp implementation does not throw.

I've labelled this as "Question" because I'm not sure what the ES6 spec says about it (it's cryptic to me).

Should rsvp throw or is the current implementation correct ?

**Comment by stefanpenner** [comment]
> I've labelled this as "Question" because I'm not sure what the ES6 spec says about it (it's cryptic to me).

It's not part of the spec, but it is a "nice thing".

As RSVP is a typically meant to be included in larger projects this functionality is disabled by default. Although I am considering enabling it be default in 4.0.

example:

```js
var rsvp = require('rsvp');
var Promise = rsvp.Promise;
Promise.reject(new Error('OMG'));
// => nothing
```

but when enabled:

```js
rsvp.on('error', console.error.bind(console));
```

```js
Promise.reject(new Error('OMG'));
// => [Error: OMG]
```

```js
Promise.reject(new Error('OMG')).catch(function(e) { });
// => nothing
```

```js
var a = Promise.reject(new Error('OMG'));

Promise.ressolve().then(function() {
  return a.catch(function(){ });
});
// => nothing
```

```js
var a = Promise.reject(new Error('OMG'));
setTimeout(function(){
  a.catch(function() { });
}, 0)

// => [Error: OMG]
```

**Comment by vicb** [comment]
@stefanpenner thanks for the detailed explanation. Closing as not a bug.

**Comment by stefanpenner** [comment]
@vicb thanks :). I believe this should be a default in 4.0 though

**Comment by stefanpenner** [comment]
i added it to the eventual 4.0 todo list https://github.com/tildeio/rsvp.js/issues/261
