### ISSUE TITLE
[Question] Getting out from promises

### ISSUE THREAD

**Issue by devel-pa** [tildeio/rsvp.js#389]
Hi,
I am using RSVP for some time and I really like it. Good job guys.
Now, I am working on a project and I'm loading some code (in fact, a lot, the full app) since the beginning with RSVP. (and with Basket.js)
The problem is that I'm stuck inside the promise chain and I want to get out somehow.
I'm not asking about the specs, don't care about them and I think kills innovation, I just didn't found a way to execute a callback at the end of promise chain and go my way and my context. I want to control, not to be controlled.
All docs found in internet explains how to enter a promise, none explain how to exit and destroy it, no garbage behind.
~~OK, is jQuery `.done` which looks like is forbidden in the world of specs, but what the heck?~~
Thanks

PS: I want my code crash here and now, not in a hidden handler of a any used library.

**Comment by stefanpenner** [comment]
You can use setTimeout if this is really something you actually need.

**Comment by devel-pa** [comment]
Thanks, 
I wanted a callback at the end of the promise that is not executed in the promise context.
Enter the Promise, no exit.
