### ISSUE TITLE
Newest ember-cli breaks rsvp build

### ISSUE THREAD

**Issue by ef4** [tildeio/rsvp.js#390]
If you try to build RSVP using ember-cli 0.2.5, it complains that deps are not installed and tells you to run `bower install`. But there are no dependencies in bower.json, so running `bower install` doesn't do anything.

RSVP's ember-cli dependency is expressed as `^0.2.1`, so you will hit this problem by default.

**Comment by stefanpenner** [comment]
fixing cli

**Comment by stefanpenner** [comment]
upstream fix https://github.com/ember-cli/ember-cli/pull/4142
