### ISSUE TITLE
Promise constructor binding

### ISSUE THREAD

**Issue by Turbo87** [tildeio/rsvp.js#394]
It seems that currently `this` in the resolver function of the Promise constructor is not bound to anything specific, but it could be useful if it was bound to the Promise instance. 

Here is a quick example:

```js
var promise = new RSVP.Promise(function(resolve, reject){
    var client = new XMLHttpRequest();
    client.open("GET", url);
    client.onreadystatechange = handler;
    client.responseType = "json";
    client.setRequestHeader("Accept", "application/json");
    client.send();

    function handler() {
        if (this.readyState === this.DONE) {
            if (this.status === 200) { resolve(this.response); }
            else { reject(this); }
        }
    };

    this.xhr = client;
});

// ...

promise.xhr.abort();
```

Since the Promise is wrapping the XMLHttpRequest it is not possible to call its `abort()` method since you can't get access to it. If the resolver method is bound to the Promise instance it is possible to make the XMLHttpRequest a property of the Promise and call its `abort()` method like shown above.

The Promise/A+ spec doesn't seem to specify this behavior and I haven't found anything else specifying it yet. Are there any reasons against doing it or any obvious disadvantages that I have missed?

**Comment by stefanpenner** [comment]
This is part of the ecmascript 6 spec, as it Is pivotal in enabling inheritance.

**Comment by Turbo87** [comment]
@stefanpenner thanks for the quick reply. any idea how else the above example could be solved then? I would like to abort an ic-ajax request, but it seems that this is currently not possible in any way (https://github.com/instructure/ic-ajax/issues/24).

**Comment by stefanpenner** [comment]
The promise constructor is sync, so you can pass out the xhr object be closing over a shared var.

**Comment by Turbo87** [comment]
okay, thanks!

**Comment by stefanpenner** [comment]
although I am dubious about the exposing the xhr.

```js

var xhr;
var promise = new RSVP.Promise(function(resolve, reject){
    var client = new XMLHttpRequest();
    client.open("GET", url);
    client.onreadystatechange = handler;
    client.responseType = "json";
    client.setRequestHeader("Accept", "application/json");
    client.send();

    function handler() {
        if (this.readyState === this.DONE) {
            if (this.status === 200) { resolve(this.response); }
            else { reject(this); }
        }
    };

    xhr = client; // <--
});
promise.xhr = xhr; // <--
// ...

promise.xhr.abort();
```
