### ISSUE TITLE
Trigger assuming event callbacks object is an array

### ISSUE THREAD

**Issue by asakusuma** [tildeio/rsvp.js#396]
I've run into an issue where RSVP.EventTarget.trigger has a variable `callbacks` that is an object, but is assumed by the code to be an array: https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp/events.js#L194

This causes the `callback` variable inside the for loop to be undefined, which causes an error when it's [called as a function](https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp/events.js#L197).

I traced the callbacks object back to this._promiseCallbacks, but I'm not sure how that's getting set.

I can only reproduce this in an Ember test running in phantomJS. I can't reproduce when running the test in the browser. It's caused by pretender returning a 500 for an acceptance test request.

1. Is `callbacks` always supposed to be an array? EDIT: it's an Ember object when it fails for me.
2. Would it be reasonable to check that `callback` is a function [before calling it](https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp/events.js#L197)?

**Comment by stefanpenner** [comment]
just a headsup the hole module is private, but we should fix this regardless.

**Comment by stefanpenner** [comment]
> Is callbacks always supposed to be an array? EDIT: it's an Ember object when it fails for me.

yes it should always be an array

**Comment by stefanpenner** [comment]
> Would it be reasonable to check that callback is a function before calling it?

I would prefer to figure out why we end up with an unexpected object? This seems like another bug

**Comment by asakusuma** [comment]
Ok I figured out what's going on here, the issue is not that `callbacks` is an object (it's an Ember.Array, which works apparently), the issue is this line of code in one of our tests:

```JavaScript
Ember.RSVP.on('error', Ember.RSVP.onerrorDefault);
```
Apparently `Ember.RSVP.onerrorDefault` doesn't exist anymore, and now whenever a promise is rejected after that `.on` call, you RSVP tries to call a falsy value as a function. That line of code was used to reset a workaround for using pretender to purposefully mock a failed call in order to test how the app behaves on a failed call.

The issue is actually reproducible when the tests are in the browser.

Even though eventing is technically a private API, would it be reasonable to check to make sure any callback passed to `.on()` is actually a function?

**Comment by stefanpenner** [comment]
Yup checking the callback arg to on is good. :shipit:
