### ISSUE TITLE
bower issue 

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/rsvp.js#402]
https://github.com/eviltrout/ember-performance/pull/48

**Comment by rwjblue** [comment]
I think the issue is that https://github.com/tildeio/rsvp.js/blob/master/bower.json#L9 should be `rsvp.js` instead of `dist/rsvp.js`.

**Comment by stefanpenner** [comment]
cc @fivetanley 

> I think the issue is that https://github.com/tildeio/rsvp.js/blob/master/bower.json#L9 should be rsvp.js instead of dist/rsvp.js.

no, we need 2 different ones. One for bower and one for using the repo locally.

**Comment by rwjblue** [comment]
Ya, this is what Ember does also (we keep ours in https://github.com/emberjs/ember.js/tree/master/config/package_manager_files).  It doesn't seem like this repo itself works as a bower repo though (it wouldn't be transpiled or concatted for example), so I didn't think you intended to have two...
