### ISSUE TITLE
RSVP.on('error') ignored when catch used

### ISSUE THREAD

**Issue by kylewelsby** [tildeio/rsvp.js#406]
I am trying to debug some code, and a error within a promise somewhere is being swallowed. I was hoping the `RSVP.on('error')` event would be emitted to allow exposure of the error to help with debugging. 

Sadly in this example the `.catch()` swallows the thrown error and the test does not pass.

```
  it('emits on "error"', function (done) {
    var RSVP = require('rsvp')
    RSVP.on('error', function (reason) {
      console.assert(true, reason)
      done()
    })

    new RSVP.Promise(function (resolve, reject) {
      resolve()
    }).then(function () {
      throw new Error('wrong')
    }).catch(function () {
      // RSVP.on 'error' should have been fired
    })
  })
```

**Comment by stefanpenner** [comment]
This is working as expected. For lower level instrumentation hooks, please see the readme *instrumentation* section. Which provides a rejection hook, which is potentially what you want.
