### ISSUE TITLE
Consider a Promise.any

### ISSUE THREAD

**Issue by uitgewis** [tildeio/rsvp.js#407]
Consider the following use-case for progressive enhancement of *some* UI:
```js
// Retrieve locally stored data
let getCache = () => {
 return RSVP.resolve(localStorage.getItem('key')); 
};

// Enhance local data set through a remote call
let getStore = () => {
  return new RSVP.Promise(resolve => $.ajax(...).then((data) => {
    localStorage.setItem('key', data);
    resolve(data);
  }));
}; 

// Return the first promise that fulfills (rejected or not)
return RSVP.race([ getCache(), getStore() ]) 
```

With `Promise.race` both promises will eventually be fulfilled, but the top-level promise only waits for the first and immediately fulfills itself.

It would be beneficial to have a method such as `Promise.any`, which will return on the first promise that resolved, disregarding any rejections published.

I know it does seem to deviate from what's currently being done, fulfill on rejection, but would help tremendously for these use-cases: In particular, if there is no local cache we can reject but keep going until we have *some* data to return.

**Comment by stefanpenner** [comment]
For this sort of pattern we provide RSVP.allSettled and RSVP.hashSettled

**Comment by uitgewis** [comment]
So I've seen. However, both mechanisms require both promises be fulfilled as far as I've seen.
This use case would take advantage of first-or-fail, without the explicit fail part.

Taking `RSVP.race` as an example, it would be deferring any rejections raised to the [`onRejection`](https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp/promise/race.js#L96) callback.

**Comment by stefanpenner** [comment]
Ah yes, I see. Race is unfortunately terrible.

We have so far made a policy to not add additional functionality, maybe @wycats feels differently about this case, lets see.

Until then, RSVP fully supports subclassing, where a user can augment and add any feature they wish.

Although I haven't had time to complete, https://github.com/stefanpenner/rsvp-party aims to be the junk drawer of various promise features.

**Comment by uitgewis** [comment]
I suspected something like that. 

But why do you say race is terrible?

**Comment by stefanpenner** [comment]
Well it has its purpose. But in-practice people want something like any

**Comment by uitgewis** [comment]
Well, I'm just leaving my +1 for it here then. :smile:

**Comment by wycats** [comment]
`any` and `some` imply a predicate, which is not what this is about. 

How about `first`? We might propose this to TC39 as well.

**Comment by stefanpenner** [comment]
@wycats `first` being short-hand for `firstFulfilled`
