### ISSUE TITLE
clarify expected behavior of finally

### ISSUE THREAD

**Issue by cappslock** [tildeio/rsvp.js#408]
The exact behavior of finally wasn't clear to me from the documentation, and it took a bit of tinkering to figure it out. I'd like to clarify that the observed behavior is the intended behavior, and maybe update the documents to reflect that.

For example:

```
var test = new RSVP.Promise(function (resolve, reject) {
  reject();
});

test.finally(function () {
  console.log('FINALLY');
}).then(function () {
  console.log('life goes on');
}).catch(function () {
  console.log('but you never handled that error...');
});
```

The output is:
```
FINALLY
but you never handled that error...
```

I guess from this that `finally` acts more or less as a passthrough - it will execute regardless of whether the promise is resolved or rejected and cannot change the resolution for chained listeners that take place after it. Is that correct?

**Comment by cappslock** [comment]
Elaborating a bit more, I guess the return value of finally doesn't affect the promise chain either:

```
(new RSVP.Promise(function (resolve, reject) {
    resolve('foo')
})).finally(function () {
    console.log('florb');
    return new Promise(function (resolve, reject) {
        resolve('boo');
    });
}).then(function (val) {
    console.log(val);
});
```

Logs:
```
florb
foo
```

This is interesting, and not really what I was expecting. Is this all intended behavior?

**Comment by stefanpenner** [comment]
@cappslock yes, `finally` behaves how the syntactic `finally` in JavaScript works (with one small exception, its return value cannot change the downstream value)

**Comment by cappslock** [comment]
Makes sense. Thanks for the explanation.
