### ISSUE TITLE
Provide promisify method

### ISSUE THREAD

**Issue by flyswatter** [tildeio/rsvp.js#409]
One nice feature of some other Promise libraries is a `promisify` method.

This is a fairly simple method that takes a method and the `self` argument to use, and assumes the last argument is a traditional callback (`function(err,results...)`), and returns a promise-returning async function instead.

The implementation can be pretty simple, too, maybe something like this:
```javascript
RSVP.prototype.promisify = function(asyncFn, self) {
  var rsvp = this;
  return function () {
    var fullArgs = arguments;
    return new rsvp.Promise(function (resolve, reject) {

      var cb = function() {
         var args = Array.prototype.slice.call(arguments);
         var err = args.shift();
         if (err) reject(err);
         resolve.apply(rsvp, args);
       }

       fullArgs.push(cb);
       asyncFn.apply(self, fullArgs);
    });
  }
}
```

**Comment by stefanpenner** [comment]
We provide denodify, which covers this.

**Comment by flyswatter** [comment]
Sweet!
