### ISSUE TITLE
Feature request - save Stack at point of promise creation

### ISSUE THREAD

**Issue by Iftahh** [tildeio/rsvp.js#419]
The `on('error'` handler receives `reason` and `label` - 

it would be very useful for debugging to get the stack trace at the point where the promise was created  (not at async callback that caused the error).

I figure it would be VERY easy to implement - and will help debugging generic errors very much. Its not quite the "long stack" feature that chains all the async stacks together, but its better than nothing.

For example:

in Ember if I run:

```javascript
    RSVP.on('error', function(reason, label) { error_report(reason); })

    authenticate().then(function() {   // ajax can fail here
      store.find('person', 5).then(function() {...});  // or here
      store.find('place', 6).then(function() {...});   // or here
   })
```
If/When the `on('error')` handler is activated with a reason of generic Ajax fail exception (eg. `Adapter operation failed` or similar)  then the reported error contains the stack trace of deep Ember/RSVP internals originating all the way back from a callback of an ajax call. 

But I can't tell from this stack which of the ajax calls was it that failed, so that data is almost meaningless!

**Comment by stefanpenner** [comment]
Ya it isn't hard to implement but it is literally like 100x slower on some platforms, so it would be opt in. Likely when something like the inspector has tracing enabled.

Also real errors in browsers(like chrome) don't display a user  provided stack. Which means normal errors will still appear foo-bar, although other tooling like the ember inspector could do something else.

Related, I'm pushing for console.tagStack from vendors (or similar) so the stack explorer in the debug tools is also useful. Which has some buy-in, and will lead to a much better solution in all cases.

**Comment by jonathandelgado** [comment]
@stefanpenner ETA on that?

**Comment by stefanpenner** [comment]
@jonathandelgado unsure I don't work on v8/chrome. Maybe ping someone like paul_irish

**Comment by stefanpenner** [comment]
For those interested in long stack traces. but want them to work in ever situation across all libraries, I would strongly recommend: https://github.com/mattinsler/longjohn it is a wonderful debug aide, and address the issue of single async steps supporting long-stacks and others not.
