### ISSUE TITLE
Full screen button

### ISSUE THREAD

**Issue by ignaciogros** [tildeio/rsvp.js#426]
Hi.

Thanks a lot for your library. Great work!

I might be doing something wrong, but the full screen button is not working when the reader is inside an IFRAME. I already included the "allowfullscreen" attribute...

In case I'm not doing anything wrong, a **feature request**:

If it's an embed content (the reader is inside an IFRAME), make the button open the IFRAME's "src" in a new window. 

I did it at the end of reader.min.js as a provisional solution:

`var my_ePubReader = {
	inIframe : function() {
		try {
			return window.self !== window.top;
		} catch (e) {
			return true;
		}
	},
	enableFS : function(){
		if (this.inIframe()) {
			jQuery("#fullscreen").click(function(){
				window.open(window.location.href);
			});
		}
	}
}
jQuery(function(){
	my_ePubReader.enableFS();
});`

Thank you!

**Comment by stefanpenner** [comment]
Im not entirely sure how rsvp and your example are related?

**Comment by ignaciogros** [comment]
You're entirely right. The comment should be in another project. 

Please remove this ticket if possible. It's not interesting at all here.

Sorry about that... 

Thank you.

**Comment by stefanpenner** [comment]
@ignaciogros no worries, have a great day.
