### ISSUE TITLE
hashSettled and allSettled do not return string reasons for rejected promises

### ISSUE THREAD

**Issue by laurenzlong** [tildeio/rsvp.js#429]
When I use hashSettled or allSettled to work with many promises at once, I get back objects that look like the following:

 { state: 'rejected',
     reason: [TypeError: undefined is not a function] } 

The reason is not a string, which leads to errors when I try to do something with this object.

**Comment by fivetanley** [comment]
Hi @laurenzlong, thanks for opening an issue. While RSVP and Promises A+ allow for rejecting with any value (like a number, string, etc), it is generally recommended to generate with an Error object. The Error object has a `message` property, which should be a string. The reason Errors are preferred is they have semantic meaning (something wrong happened) and most runtimes give you access to the stack (where the problem happened).

If a runtime exception happens inside the Promise, that error will be handled by `allSettled` or `hashSettled`.

So, I don't think this is a bug, so I'm closing the issue. Let me know if you have any questions and I'll try to answer them.

To properly handle this, you may want to try using the `reason.message` property instead.

**Comment by laurenzlong** [comment]
That makes sense, thank you! Also it seems like I must write "reject(err.message)", not "reject(err)". (Where err is an Error object). It would be great if both could work.

**Comment by fivetanley** [comment]
Both do work, but I would recommend you reject with an error and then in your handler code, extract the message:

```javascript
RSVP.reject(new Error('whoops!')).catch(function(err) {
  console.log('was rejected with', err.message);
});
```

Rejecting with Error objects seems to be the most common pattern used with promises, so it's nice to have consistent code to handle it.

**Comment by laurenzlong** [comment]
Thanks for the code snippet! I'm still unsure of how this would tie in with using allSettled, and would appreciate your insight. 

```
function operation() {
    var err = new Error('whoops!');
    return RSVP.reject(err);
}

var op1 = operation();
var op2 = operation();

RSVP.allSettled([op1, op2]).then( function(results) {
    console.log(results); 
// [{state: 'rejected', reason: [Error: whoops!}, {state: 'rejected', reason: [Error: whoops!}]     
});
```

In the above code snippet, results now contains a non-string for reason. Can you how I can prevent this other than replacing line 3 with 'return RSVP.reject(err.message)'?
