### ISSUE TITLE
PhantomJS + rejected promise + finally - test failures with assert.deepEqual

### ISSUE THREAD

**Issue by raido** [tildeio/rsvp.js#433]
There is an issue with PhantomJS + complex promise chain with multiple catches + finally would fail unit test.

Whenever finallys are removed, tests will pass - only with finallys it breaks, because PhantomJS adds stack + other information on the thrown user error object.

https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp/promise.js#L447
https://github.com/tildeio/rsvp.js/blob/v3.1.0/lib/rsvp/promise.js#L492

I have reproduction of this here - https://github.com/raido/rsvp-phatomjs-bug - look app/services/break-me.js and related unit test.

@stefanpenner

**Comment by raido** [comment]
It actually fails with simple `new RSVP.reject(errorObject).finally(...)` - does not need complex promise chain at all.

**Comment by stefanpenner** [comment]
@raido interesting, will take a look

**Comment by stefanpenner** [comment]
@domenic I'm curious if you have thoughts on this.

I believe per proposed spec, `finally` should be implemented more or less like:

```js
    var promise = this;
    var constructor = promise.constructor;

    return promise.then(function(value) {
      return constructor.resolve(callback()).then(function(){
        return value;
      });
    }, function(reason) {
      return constructor.resolve(callback()).then(function(){
        throw reason;
      });
    });
  }
```

Unfortunately, phantomjs does bad things, the `throw` in the failure scenario adds additional information onto the `reason`, causing downstream deepEquals to fail, but only in this broken browser. My gut feeling is to say `throw` is the right approach, and its to bad that phantom does the wrong thing. Would you agree?

**Comment by domenic** [comment]
Yes, that sounds right to me.

**Comment by raido** [comment]
Yes, that's what I thought too.

`assert.equal(errorObject.property, expectedError.property)` - is way to go with such use case.
