### ISSUE TITLE
v3.3.0 - RSVP undefined after module import

### ISSUE THREAD

**Issue by edmundito** [tildeio/rsvp.js#434]
Hi, I'm seeing a strange issue when I update to v3.3.0.

Previously I had the following, using modules and babel:
```js
import RSVP from 'rsvp'
console.log(RSVP)
```

In 3.3.0, the console.log will print `undefined`. However, I switch it to:

```js
const RSVP = require('rsvp')
```

Then it works!

Unfortunately, I have not been able to narrow down the cause. This only seems to occur in the test environment (node, mocha) when it is running my files directly in node. When running the client-side scripts, the `import` statement imports RSVP just fine, though.

**Comment by stefanpenner** [comment]
i see the issue i believe, will address after dinner.

**Comment by stefanpenner** [comment]
@edmundito can you share an example of how you are using babel. I want to make sure i handle that case for sure.

**Comment by stefanpenner** [comment]
https://github.com/tildeio/rsvp.js/pull/435 may address, but I would like a reproduction so I can verify.

**Comment by stefanpenner** [comment]
Alright, im abit confused. Earlier we only provided property exports, and no default. Can you share your setup that demonstrated the issue, I need to understand exactly how you (in node land) are requiring stuff.

**Comment by stefanpenner** [comment]
last version was:

```js
    if (typeof define === 'function' && define['amd']) {
      define(function() { return lib$rsvp$umd$$RSVP; });
    } else if (typeof module !== 'undefined' && module['exports']) {
      module['exports'] = lib$rsvp$umd$$RSVP;
    } else if (typeof lib$rsvp$platform$$default !== 'undefined') {
      lib$rsvp$platform$$default['RSVP'] = lib$rsvp$umd$$RSVP;
    }
```

This version is:

```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define(['exports'], factory) :
  (factory((global.RSVP = global.RSVP || {})));
}(this, (function (exports) { 'use strict';
```

+

```
Object.defineProperty(exports, '__esModule', { value: true });
```

Which most likely hints to babel to do the right thing, and not default the module.export as both default and props.

**Comment by stefanpenner** [comment]
I suspect https://github.com/tildeio/rsvp.js/pull/435 now addresses the issue.

**Comment by edmundito** [comment]
@stefanpenner Thanks, I was just able to confirm that #435 fixes the issue. 👍 

In any case, here is a basic setup to reproduce the issue:
https://gist.github.com/edmundito/643f827ee72c4c08b9b019cbecf174bc
