### ISSUE TITLE
jsnext

### ISSUE THREAD

**Issue by salzhrani** [tildeio/rsvp.js#439]
we ran into an issue similar to [this](https://github.com/webpack/webpack/issues/2902)
and It seems that `jsnext:main` entry should to transpiled code that has module syntax, not `es6` code. currently the code in `lib` is es6 and it makes safari sad.

**Comment by stefanpenner** [comment]
> and It seems that jsnext:main entry should to transpiled code that has module syntax, not es6 code. currently the code in lib is es6 and it makes safari sad.

I don't believe that is the point of `jsnext:main`

**Comment by salzhrani** [comment]
It is what bundlers like webpack and rollup are expecting. 

ref:
https://github.com/reactjs/redux/issues/1042
https://github.com/jsforum/jsforum/issues/5

**Comment by stefanpenner** [comment]
> jsforum/jsforum#5

doesn't actually come to conclusion, and one of the last points raised is: https://github.com/jsforum/jsforum/issues/5#issuecomment-182036073

@Rich-Harris @caridy whats-up with with `jsnext:main` referring to ES2015 modules only subset of jsnext? Something smells very fishy about that. `modules:main` or something makes sense.

On our side, we have always treated as `jsnext` mains entry points requiring a full transpile.

**Comment by stefanpenner** [comment]
`3.4.0` now points to a bundle with only `exports` statements: https://github.com/tildeio/rsvp.js/commit/28e5753f5094c254171a38ee963e039acc2bfbc3
