### ISSUE TITLE
Silently swallows runtime exceptions

### ISSUE THREAD

**Issue by nilliams** [tildeio/rsvp.js#440]
See:  http://requirebin.com/?gist=a6d249325c9a1d80b6512da6fd47fadd

Also see examples where catch handlers are accidentally omitted:

- http://requirebin.com/?gist=522f6caf188acf871ad064663764defb
- http://requirebin.com/?gist=14017270a8600b86bbc40a78e4730ed8

More detail/history in this (downstream?) thread: https://github.com/stefanpenner/es6-promise/issues/70

**Comment by stefanpenner** [comment]
see readme: https://github.com/tildeio/rsvp.js#error-handling
