### ISSUE TITLE
AllSettled only returns objects with the state "fulfilled"

### ISSUE THREAD

**Issue by mkampmey** [tildeio/rsvp.js#445]
Hi!
I tried using XMLHttpRequests in combination with rsvp.js. Escpecially I need the allSettled function. Can you take a look at [this](https://jsfiddle.net/fzup8n45/1/) fiddle? After calling the allSettled function each result object has the state fulfilled although the request fails.

**Comment by stefanpenner** [comment]
In your example, it appears you are recovering from both of your rejected promises by using `catch` but not re-throwing the exception.

If you `throw` in the catch, all is well.


```js
 }).catch(function(error) {
                console.log("failure")
                throw error;
            });
```
