### ISSUE TITLE
promote all input validations to user facing api from internal Enumerators

### ISSUE THREAD

**Issue by bekzod** [tildeio/rsvp.js#457]
right now there is `_validateInput` and `_validationError` in all Enumerators so my suggestion is to move them to upper level api (e.g. hash, all ...) 
why ? 
* Enumerators will be cleaner, each Enumerator is extending its custom validation and message anyway
* there is already validations in map/filter helpers for map/filter function existence so validations will be in one place

**Comment by stefanpenner** [comment]
@bekzod I'm down, assuming the following constraints:

* minimal byte-size increase
* minimal performance loss.

**Comment by bekzod** [comment]
it is implemented, closing the issue
