### ISSUE TITLE
Execution per batch

### ISSUE THREAD

**Issue by toncho11** [tildeio/rsvp.js#480]
Hi,

I need to download and quickly process 288 json files, so I am using this code:

```
var promises = times.map(function(id){
  var file = "myurl?time=" + id;
  console.log(file);
  return jQuery.getJSON(file);
});

RSVP.all(promises).then(function(posts) {
// posts contains an array of results for the given promises
for(i=0; i< posts.length; i++)
{
	result += posts[i];
 }
console.log("done processing");
			  
}).catch(function(reason){
console.log("Promise json get data error: " + reason);
});
```

In Chrome I see that files are downloaded by batches of 6. 6 files start downloading in parallel and at some point (before the first 6 are done) the second batch of 6 files download is started and so on. So it takes 40 seconds. 

Is this normal behavior? Can I speed it up and avoid batching and force 288 parallel downloads?

**Comment by bekzod** [comment]
@toncho11 that is is limitation of browser, browser has limit for concurrent open XHR requests per site which varies per browser :), RSVP itself doesn't have any limit on concurrent job

**Comment by stefanpenner** [comment]
ya as @bekzod mentioned, RSVP has not built-in batching, what you are seeing is a hard limit imposed by the browser.
