### ISSUE TITLE
should we worry about edge cases when rejections has no content

### ISSUE THREAD

**Issue by bekzod** [tildeio/rsvp.js#482]
should we worry about following ? 

following code will pass test
```javascript
it('pass test', function(done) {
      Promise.reject().catch(done);
});
```

following code `RSVP.hash` will also pass in rejection case if rejection will have no content
```javascript
it('works with a truthy value', function(done) {
      RSVP.hash({foo: 1}).then(function(results) {
        assert.deepEqual(results.foo, true);
        done();
      }).catch(done);
});
```

to take into account such cases test could be written
```javascript
it('works with a truthy value', function() {
      expect(1)
      return RSVP.hash({foo: 1}).then(function(results) {
        assert.deepEqual(results.foo, true);
      });
});
```

let me know your thoughts, am I being paranoid here :D ?
@stefanpenner

**Comment by stefanpenner** [comment]
> let me know your thoughts, am I being paranoid here :D ?

you concerns seems legitimate!

**Comment by bekzod** [comment]
Let me know if you want tests reworked as above
