### ISSUE TITLE
Upgrade Outdated Deferred Example

### ISSUE THREAD

**Issue by justsml** [tildeio/rsvp.js#488]
How do you feel about a PR removing, changing or adding a note to the README's Deferred section? 

IMHO deferred is not a recommended usage pattern. 
My main concerns w/ Deferred's are they're not chain-able; make Promises seem more confusing (extra brain-space for additional API); and they forgo the functional & scoping benefits of Promises with a useless layer of indirection.

The wrapping layer is easy to avoid. However it's hard to completely avoid the need for 'unpacking' (returning a promise w/ it's resolve/reject methods). Typically this is for event or stream Promise work. 

> Here's a native example which avoids the extra wrapper object w/ only `new Promise` + variable hoisting:

```js
// promised() externalizes Promises guts
// @returns [promise, resolve, reject]
const promised = () => {
  var resolve, reject, promise = new RSVP.Promise((_resolve, _reject) => {resolve = _resolve; reject = _reject })
  return [promise, resolve,  reject]
}
// Usage Example
let [promise, resolve,  reject] = promised()
promise.then(console.log.bind(console, 'Hello '))
resolve(42)
// => Hello 42
```

**Comment by stefanpenner** [comment]
> How do you feel about a PR removing,

I think we should keep it, it is largely a sibling to `RSVP.denodify` for use when interopting with the non-promise world.

>  However it's hard to completely avoid the need

This is why we provide it.

> changing or adding a note to the README's Deferred section?

docs seem to describe this, but they can always be improved 
https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp/defer.js#L3-L6

I think merging the API doc on deferred, and the Readme section on deferred may address your concerns, and I would be encourage that change.

**Comment by justsml** [comment]
@stefanpenner thx for the info.
And link to the inline docs. Makes more sense.

I agree on merging the docs, I'll try take a swing at a PR later this week.
