### ISSUE TITLE
TaskJS is no longer available

### ISSUE THREAD

**Issue by sukima** [tildeio/rsvp.js#508]
The reference to [TaskJS](http://taskjs.org/) now points to a bogus site. [tj/co](https://github.com/tj/co) is a good alternative. Considering async/await is still not compatible (https://github.com/emberjs/rfcs/issues/175) in some cases and that co-routines are a desired (see #500) feature perhaps we should link to another library (like https://github.com/tj/co and https://github.com/akatov/ember-co)? Or whip up a PR with a `RSVP.coroutine()` API?

![rsvp-wtf](https://user-images.githubusercontent.com/70075/31144984-5c7f2374-a850-11e7-8999-6b78e2da39c3.gif)

**Comment by formigarafa** [comment]
found it! https://github.com/mozilla/task.js

**Comment by sukima** [comment]
OMG Even **their** readme links to the defunct taskjs.org !!!
