### ISSUE TITLE
Finally does not execute synchronously

### ISSUE THREAD

**Issue by neilbaylor** [tildeio/rsvp.js#512]
I am noticing that `finally` does not execute synchronously with `then`, as one would expect

example:

```
function finish () {
   console.log('finally');
}

for(var i=0; i < 100; i++) {
   doSomethingAsync.then(function () {
      console.log('then');
   }).finally(finish);
}
```
does not always output
```
then
finally
then
finally
... (98 more times)
```
occasionally, i will see 
```
then
then
finally
finally
```

if i refactor to 
```
function finish () {
   console.log('finally');
}

for(var i=0; i < 100; i++) {
   doSomethingAsync.then(function () {
      console.log('then');
      finish();
   });
}
```

i will always see:
```
then
finally
then
finally
... (98 more times)
```

Is there something like a `setTImeout(finally, 0)` somewhere in there? It is acting like there is.

I am seeing this behaviour in an Ember app (v2.14.1) running on Chrome  62.0.3202.94 (Official Build) (64-bit) on OSX Sierra

**Comment by stefanpenner** [comment]
> I am noticing that finally does not execute synchronously with then, as one would expect

 I would not expect this.

**Comment by stefanpenner** [comment]
I do actually not expect the output you are getting, and my tests confirm. I believe your example is incomplete.

In your example I would expect the following:

1. 100 then's
2. followed by 100 finally

Code:
```
var doSomethingAsync  = require('rsvp').Promise.resolve();

for (let i = 0; i < 100;i ++) {
  doSomethingAsync.then(x => console.log(`then ${i}`)).then(() => console.log(`finally ${i}`));
}
```

Output:
<details>
<pre>
then 0
then 1
then 2
then 3
then 4
then 5
then 6
then 7
then 8
then 9
then 10
then 11
then 12
then 13
then 14
then 15
then 16
then 17
then 18
then 19
then 20
then 21
then 22
then 23
then 24
then 25
then 26
then 27
then 28
then 29
then 30
then 31
then 32
then 33
then 34
then 35
then 36
then 37
then 38
then 39
then 40
then 41
then 42
then 43
then 44
then 45
then 46
then 47
then 48
then 49
then 50
then 51
then 52
then 53
then 54
then 55
then 56
then 57
then 58
then 59
then 60
then 61
then 62
then 63
then 64
then 65
then 66
then 67
then 68
then 69
then 70
then 71
then 72
then 73
then 74
then 75
then 76
then 77
then 78
then 79
then 80
then 81
then 82
then 83
then 84
then 85
then 86
then 87
then 88
then 89
then 90
then 91
then 92
then 93
then 94
then 95
then 96
then 97
then 98
then 99
finally 0
finally 1
finally 2
finally 3
finally 4
finally 5
finally 6
finally 7
finally 8
finally 9
finally 10
finally 11
finally 12
finally 13
finally 14
finally 15
finally 16
finally 17
finally 18
finally 19
finally 20
finally 21
finally 22
finally 23
finally 24
finally 25
finally 26
finally 27
finally 28
finally 29
finally 30
finally 31
finally 32
finally 33
finally 34
finally 35
finally 36
finally 37
finally 38
finally 39
finally 40
finally 41
finally 42
finally 43
finally 44
finally 45
finally 46
finally 47
finally 48
finally 49
finally 50
finally 51
finally 52
finally 53
finally 54
finally 55
finally 56
finally 57
finally 58
finally 59
finally 60
finally 61
finally 62
finally 63
finally 64
finally 65
finally 66
finally 67
finally 68
finally 69
finally 70
finally 71
finally 72
finally 73
finally 74
finally 75
finally 76
finally 77
finally 78
finally 79
finally 80
finally 81
finally 82
finally 83
finally 84
finally 85
finally 86
finally 87
finally 88
finally 89
finally 90
finally 91
finally 92
finally 93
finally 94
finally 95
finally 96
finally 97
finally 98
finally 99
</pre>
</details>

**Comment by stefanpenner** [comment]
Some more examples:

* sequentially fulfill, and they sequentially resolve:

```
var RSVP = require('RSVP');

for (let i = 0; i < 100;i ++) {
  new RSVP.Promise(resolve => setTimeout(resolve, i * 10)).then(x => console.log(`then ${i}`)).then(() => console.log(`finally ${i}`));
}
```

output:

<detail>
<pre>
then 0
finally 0
then 1
finally 1
then 2
finally 2
then 3
finally 3
then 4
finally 4
then 5
finally 5
then 6
finally 6
then 7
finally 7
then 8
finally 8
then 9
finally 9
then 10
finally 10
then 11
finally 11
then 12
finally 12
then 13
finally 13
then 14
finally 14
then 15
finally 15
then 16
finally 16
then 17
finally 17
then 18
finally 18
then 19
finally 19
then 20
finally 20
then 21
finally 21
then 22
finally 22
then 23
finally 23
then 24
finally 24
then 25
finally 25
then 26
finally 26
then 27
finally 27
then 28
finally 28
then 29
finally 29
then 30
finally 30
then 31
finally 31
then 32
finally 32
then 33
finally 33
then 34
finally 34
then 35
finally 35
then 36
finally 36
then 37
finally 37
then 38
finally 38
then 39
finally 39
then 40
finally 40
then 41
finally 41
then 42
finally 42
then 43
finally 43
then 44
finally 44
then 45
finally 45
then 46
finally 46
then 47
finally 47
then 48
finally 48
then 49
finally 49
then 50
finally 50
then 51
finally 51
then 52
finally 52
then 53
finally 53
then 54
finally 54
then 55
finally 55
then 56
finally 56
then 57
finally 57
then 58
finally 58
then 59
finally 59
then 60
finally 60
then 61
finally 61
then 62
finally 62
then 63
finally 63
then 64
finally 64
then 65
finally 65
then 66
finally 66
then 67
finally 67
then 68
finally 68
then 69
finally 69
then 70
finally 70
then 71
finally 71
then 72
finally 72
then 73
finally 73
then 74
finally 74
then 75
finally 75
then 76
finally 76
then 77
finally 77
then 78
finally 78
then 79
finally 79
then 80
finally 80
then 81
finally 81
then 82
finally 82
then 83
finally 83
then 84
finally 84
then 85
finally 85
then 86
finally 86
then 87
finally 87
then 88
finally 88
then 89
finally 89
then 90
finally 90
then 91
finally 91
then 92
finally 92
then 93
finally 93
then 94
finally 94
then 95
finally 95
then 96
finally 96
then 97
finally 97
then 98
finally 98
then 99
finally 99
</pre>
</detail>

**Comment by stefanpenner** [comment]
Anyways, I tested a-bunch of scenarios and the output is as I would expect. If you can provide a concrete example that violates the above ^, I'll gladly investigate.

**Comment by neilbaylor** [comment]
I am confused by the examples you posted

Why are you doing then chained to then ?

It should be then chained to finally

**Comment by neilbaylor** [comment]
This
```
doSomethingAsync.then(function () {
      console.log('then');
      finish();
   });
```
should be equal to
```
doSomethingAsync.then(function () {
      console.log('then');
   }).finally(finish);
```

**Comment by neilbaylor** [comment]
This *might* be the way promises are expected to function, but that would be a real shocker to me, it should be a "tight run loop" as it would be with callbacks in JS.

**Comment by neilbaylor** [comment]
uggh, just confirmed that native promises do this as well
```
for(var i=0; i < 100; i++) {
    let p = new Promise(function (resolve, reject) {
		resolve();
    });
    p.then(function (i) { console.log(i) }.bind(null, i)).then(function (i) { console.log(i) }.bind(null, i))
}
```
Wow, that is really not nice for users, oh well - thanks!

**Comment by neilbaylor** [comment]
If you're curious https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Timing

Apparently its a feature

**Comment by stefanpenner** [comment]
> Why are you doing then chained to then ?

`finally` is just `then` under the hood:

https://github.com/tildeio/rsvp.js/blob/12b646c01623a57c4eff37b9b9864e6e892dd025/lib/rsvp/promise.js#L226-L232



> Apparently its a feature - which is crazy to me - so "anti JS" to break the event loop.

👍  on digging deeper.

---

> Apparently its a feature - which is crazy to me - so "anti JS" to break the event loop.

This feature is no accident.

> there is nothing async in the first then so the second one should fire immediately.

Actually, this would be hazardous and promises where specifically designed to avoid this common problem. Ones code should not perform differently based on if the data is cached or not.

I believe @isaacs (of npm/node fame) wrote a great description of this problem: http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

**Comment by neilbaylor** [comment]
Not sure i agree that it would be hazardous, still feels bizarre to me given the nature of JS and the event loop, but i do agree that making everything async makes things simpler.

And thanks for the link, nice having some historical context!
